version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: algo_web
    command: >
      bundle exec puma -C config/puma.rb
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/rails:cached
      - bundle:/usr/local/bundle
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/0
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/algo_scalper_api
      DISABLE_TRADING_SUPERVISOR: "true"

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: algo_worker
    entrypoint: ["ruby"]
    command: ["config/worker_boot.rb"]
    env_file:
      - .env
    environment:
      RAILS_ENV: development
      WORKER_MODE: "true"
      DISABLE_TRADING_SUPERVISOR: "false"
      REDIS_URL: redis://redis:6379/0
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/algo_scalper_api
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/rails:cached
      - bundle:/usr/local/bundle

  redis:
    image: redis:7-alpine
    container_name: algo_redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:15
    container_name: algo_pg
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: algo_scalper_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
  redis_data:
  bundle:
